parameters:
#    dev_fine_google_calander_events.example.class: DevFine\GoogleCalanderEventsBundle\Example

services:
#    dev_fine_google_calander_events.example:
#        class: %dev_fine_google_calander_events.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
